pipeline {
    agent {
        label 'AGENT-1'
    }
    options {
        timeout(time: 1, unit: 'MINUTES')
        disableConcurrentBuilds()
    }
    stages {
        stage('Init') {
            steps {
                sh "echo this is Build"
                sh 'env'
            }
        }
        stage('Test') {
            steps {
                sh "echo this is Test"
                sh 'sleep 10'
            }
        }
        stage('Deploy') {
            steps {
                sh "echo this is Deploy"
            }
        }